# Generated by Django 3.2.5 on 2021-08-12 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('obs', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=50)),
                ('coord', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ages', models.CharField(choices=[('Bezerro', 'Bezerro'), ('Boi', 'Boi'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Vaca', 'Vaca')], default='Vaca', max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('Amarelo', 'Amarelo'), ('Azul', 'Azul'), ('Branco', 'Branco'), ('Laranja', 'Laranja'), ('Preto', 'Preto'), ('Rosa', 'Rosa'), ('Verde', 'Verde'), ('Vermelho', 'Vermelho')], default='Azul', max_length=50)),
                ('aquisiton_date', models.DateField(blank=True, default='11/08/21', null=True)),
                ('buy_age', models.IntegerField(blank=True, default=1, null=True)),
                ('child_quant', models.IntegerField(blank=True, default=0, null=True)),
                ('last_child_birth', models.DateField(blank=True, default='11/08/21', null=True)),
                ('vac', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50, null=True)),
                ('nota_fiscal', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50, null=True)),
                ('obs', models.TextField(blank=True, max_length=1000)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cows.farm')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cows.owner')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
