# Generated by Django 3.2.5 on 2021-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0003_auto_20210811_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='coord',
            new_name='coord_lat',
        ),
        migrations.AddField(
            model_name='farm',
            name='coord_long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='aquisiton_date',
            field=models.DateField(blank=True, default='17/08/21', null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='last_child_birth',
            field=models.DateField(blank=True, default='17/08/21', null=True),
        ),
    ]
